/**
 * Seed GHIGLIOTTINA — 300 parole con frasi-indizio.
 * Ogni entry = una parola + frase che suggerisce la parola in modo non esplicito.
 * Lancialo con: `npm run db:seed-ghigliottina`
 *
 * Categoria dedicata "Ghigliottina". Le domande hanno:
 *   type: GHIGLIOTTINA, text: frase-indizio, openAnswer: parola corretta.
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type Entry = { word: string; hint: string; difficulty: "EASY" | "MEDIUM" | "HARD" };

// 300 frasi-indizio. `word` è la parola da indovinare, `hint` è la frase-indizio.
const ENTRIES: Entry[] = [
  // --- EASY (100) --- semplici, oggetti comuni, concetti quotidiani
  { word: "CUORE",     hint: "Organo che batte nel petto",                                   difficulty: "EASY" },
  { word: "LUNA",      hint: "Compagna delle notti stellate",                                difficulty: "EASY" },
  { word: "SOLE",      hint: "Brilla caldo a mezzogiorno",                                   difficulty: "EASY" },
  { word: "MARE",      hint: "Si estende blu fino all'orizzonte",                            difficulty: "EASY" },
  { word: "CASA",      hint: "Dove si torna la sera",                                        difficulty: "EASY" },
  { word: "LIBRO",     hint: "Si sfoglia pagina dopo pagina",                                difficulty: "EASY" },
  { word: "PANE",      hint: "Profuma appena sfornato",                                      difficulty: "EASY" },
  { word: "ACQUA",     hint: "Dissetante senza colore",                                      difficulty: "EASY" },
  { word: "FUOCO",     hint: "Scoppietta nel camino",                                        difficulty: "EASY" },
  { word: "NEVE",      hint: "Ricopre tutto di bianco",                                      difficulty: "EASY" },
  { word: "VENTO",     hint: "Soffia tra i rami",                                            difficulty: "EASY" },
  { word: "CIELO",     hint: "Sopra le nostre teste",                                        difficulty: "EASY" },
  { word: "STELLA",    hint: "Punta luminosa nel buio",                                      difficulty: "EASY" },
  { word: "FIORE",     hint: "Profuma e colora il prato",                                    difficulty: "EASY" },
  { word: "ALBERO",    hint: "Ha radici, tronco e foglie",                                   difficulty: "EASY" },
  { word: "TERRA",     hint: "Il pianeta che abitiamo",                                      difficulty: "EASY" },
  { word: "OCCHIO",    hint: "Serve a vedere il mondo",                                      difficulty: "EASY" },
  { word: "MANO",      hint: "Stringe, saluta, accarezza",                                   difficulty: "EASY" },
  { word: "PIEDE",     hint: "Calza la scarpa",                                              difficulty: "EASY" },
  { word: "BOCCA",     hint: "Mastica e sorride",                                            difficulty: "EASY" },
  { word: "NASO",      hint: "Serve a sentire i profumi",                                    difficulty: "EASY" },
  { word: "CAPELLI",   hint: "Crescono in testa",                                            difficulty: "EASY" },
  { word: "GATTO",     hint: "Fa le fusa sul divano",                                        difficulty: "EASY" },
  { word: "CANE",      hint: "Il miglior amico dell'uomo",                                   difficulty: "EASY" },
  { word: "UCCELLO",   hint: "Cinguetta e vola",                                             difficulty: "EASY" },
  { word: "PESCE",     hint: "Nuota senza respirare aria",                                   difficulty: "EASY" },
  { word: "CAVALLO",   hint: "Galoppa nella prateria",                                       difficulty: "EASY" },
  { word: "LEONE",     hint: "Re della savana",                                              difficulty: "EASY" },
  { word: "PIZZA",     hint: "Italiana, rotonda, con pomodoro",                              difficulty: "EASY" },
  { word: "PASTA",     hint: "Si condisce col sugo",                                         difficulty: "EASY" },
  { word: "LATTE",     hint: "Bianco, dalla mucca",                                          difficulty: "EASY" },
  { word: "CAFFE",     hint: "Energia al mattino",                                           difficulty: "EASY" },
  { word: "ZUCCHERO",  hint: "Rende dolci le bevande",                                       difficulty: "EASY" },
  { word: "SALE",      hint: "Insaporisce i cibi",                                           difficulty: "EASY" },
  { word: "MELA",      hint: "Frutto di Newton",                                             difficulty: "EASY" },
  { word: "BANANA",    hint: "Giallo e piace alle scimmie",                                  difficulty: "EASY" },
  { word: "LIMONE",    hint: "Giallo e aspro",                                               difficulty: "EASY" },
  { word: "FRAGOLA",   hint: "Rossa con i puntini",                                          difficulty: "EASY" },
  { word: "UVA",       hint: "Si raccoglie in autunno",                                      difficulty: "EASY" },
  { word: "ARANCIA",   hint: "Colore e frutto allo stesso tempo",                            difficulty: "EASY" },
  { word: "TAVOLO",    hint: "Lo apparecchi per mangiare",                                   difficulty: "EASY" },
  { word: "SEDIA",     hint: "Ci si siede sopra",                                            difficulty: "EASY" },
  { word: "LETTO",     hint: "Per dormire e sognare",                                        difficulty: "EASY" },
  { word: "PORTA",     hint: "Si apre e si chiude",                                          difficulty: "EASY" },
  { word: "FINESTRA",  hint: "Dà aria e luce",                                               difficulty: "EASY" },
  { word: "CHIAVE",    hint: "Apre la serratura",                                            difficulty: "EASY" },
  { word: "OROLOGIO",  hint: "Segna il tempo",                                               difficulty: "EASY" },
  { word: "SCARPA",    hint: "Protegge i piedi",                                             difficulty: "EASY" },
  { word: "CAPPOTTO",  hint: "Copre d'inverno",                                              difficulty: "EASY" },
  { word: "MACCHINA",  hint: "Quattro ruote e un motore",                                    difficulty: "EASY" },
  { word: "TRENO",     hint: "Viaggia sui binari",                                           difficulty: "EASY" },
  { word: "AEREO",     hint: "Vola ad alta quota",                                           difficulty: "EASY" },
  { word: "NAVE",      hint: "Solca gli oceani",                                             difficulty: "EASY" },
  { word: "STRADA",    hint: "Porta da un punto all'altro",                                  difficulty: "EASY" },
  { word: "PONTE",     hint: "Attraversa il fiume",                                          difficulty: "EASY" },
  { word: "CITTA",     hint: "Grande centro abitato",                                        difficulty: "EASY" },
  { word: "PAESE",     hint: "Più piccolo di una città",                                     difficulty: "EASY" },
  { word: "SCUOLA",    hint: "Dove si studia ogni giorno",                                   difficulty: "EASY" },
  { word: "LAVORO",    hint: "Occupa le giornate degli adulti",                              difficulty: "EASY" },
  { word: "AMORE",     hint: "Sentimento che fa battere il cuore",                           difficulty: "EASY" },
  { word: "AMICIZIA",  hint: "Legame profondo non di sangue",                                difficulty: "EASY" },
  { word: "FAMIGLIA",  hint: "Genitori, fratelli e nonni",                                   difficulty: "EASY" },
  { word: "BAMBINO",   hint: "Piccolo essere umano",                                         difficulty: "EASY" },
  { word: "MAMMA",     hint: "Ci ha messi al mondo",                                         difficulty: "EASY" },
  { word: "PAPA",      hint: "Genitore maschio di famiglia",                                 difficulty: "EASY" },
  { word: "NONNO",     hint: "Il papà del papà",                                             difficulty: "EASY" },
  { word: "FRATELLO",  hint: "Figlio degli stessi genitori",                                 difficulty: "EASY" },
  { word: "SORELLA",   hint: "Sua madre è la tua",                                           difficulty: "EASY" },
  { word: "AMICO",     hint: "Ti è vicino nel bisogno",                                      difficulty: "EASY" },
  { word: "FESTA",     hint: "Si balla e si mangia la torta",                                difficulty: "EASY" },
  { word: "REGALO",    hint: "Si riceve col fiocco",                                         difficulty: "EASY" },
  { word: "NATALE",    hint: "Il 25 dicembre",                                               difficulty: "EASY" },
  { word: "PASQUA",    hint: "L'uovo di cioccolato",                                         difficulty: "EASY" },
  { word: "ESTATE",    hint: "La stagione delle vacanze",                                    difficulty: "EASY" },
  { word: "INVERNO",   hint: "Fa freddo e scende la neve",                                   difficulty: "EASY" },
  { word: "PRIMAVERA", hint: "Rifioriscono gli alberi",                                      difficulty: "EASY" },
  { word: "AUTUNNO",   hint: "Le foglie cadono a terra",                                     difficulty: "EASY" },
  { word: "PIOGGIA",   hint: "Bagna le strade",                                              difficulty: "EASY" },
  { word: "TEMPORALE", hint: "Tuoni, fulmini e pioggia forte",                               difficulty: "EASY" },
  { word: "NUVOLA",    hint: "Soffice e bianca nel cielo",                                   difficulty: "EASY" },
  { word: "ARCOBALENO",hint: "Appare dopo la pioggia",                                       difficulty: "EASY" },
  { word: "MONTAGNA",  hint: "Si sale con gli scarponi",                                     difficulty: "EASY" },
  { word: "FIUME",     hint: "Scorre verso il mare",                                         difficulty: "EASY" },
  { word: "LAGO",      hint: "Specchio d'acqua circondato di terra",                         difficulty: "EASY" },
  { word: "SPIAGGIA",  hint: "Sabbia, ombrellone e onde",                                    difficulty: "EASY" },
  { word: "BOSCO",     hint: "Tanti alberi fitti insieme",                                   difficulty: "EASY" },
  { word: "PRATO",     hint: "Verde erba da sdraiare",                                       difficulty: "EASY" },
  { word: "SABBIA",    hint: "Costruisci castelli in riva",                                  difficulty: "EASY" },
  { word: "CAPPELLO",  hint: "Copre la testa",                                               difficulty: "EASY" },
  { word: "BORSA",     hint: "Ci metti dentro le tue cose",                                  difficulty: "EASY" },
  { word: "PENNA",     hint: "Serve per scrivere",                                           difficulty: "EASY" },
  { word: "LUCE",      hint: "Illumina la stanza",                                           difficulty: "EASY" },
  { word: "SUONO",     hint: "Lo senti con le orecchie",                                     difficulty: "EASY" },
  { word: "COLORE",    hint: "Rosso, blu, giallo...",                                        difficulty: "EASY" },
  { word: "MUSICA",    hint: "Si ascolta con piacere",                                       difficulty: "EASY" },
  { word: "CANZONE",   hint: "Parole e melodia",                                             difficulty: "EASY" },
  { word: "BALLO",     hint: "Si muove a tempo",                                             difficulty: "EASY" },
  { word: "RISATA",    hint: "Scoppia quando ti diverti",                                    difficulty: "EASY" },
  { word: "SOGNO",     hint: "Lo fai dormendo",                                              difficulty: "EASY" },
  { word: "BACIO",     hint: "Si dà con le labbra",                                          difficulty: "EASY" },
  { word: "SORRISO",   hint: "Esprime felicità",                                             difficulty: "EASY" },
  { word: "ABBRACCIO", hint: "Stretta affettuosa",                                           difficulty: "EASY" },

  // --- MEDIUM (100) --- concetti meno immediati, riferimenti culturali
  { word: "GIARDINO",  hint: "L'Eden era così",                                              difficulty: "MEDIUM" },
  { word: "NAVIGARE",  hint: "Quel che faceva Ulisse, quel che si fa online",                difficulty: "MEDIUM" },
  { word: "RICORDO",   hint: "Ciò che resta quando il tempo passa",                          difficulty: "MEDIUM" },
  { word: "DESTINO",   hint: "La strada già scritta",                                        difficulty: "MEDIUM" },
  { word: "PROMESSA",  hint: "Un patto con se stessi o con l'altro",                         difficulty: "MEDIUM" },
  { word: "SPECCHIO",  hint: "Riflette chi sei",                                             difficulty: "MEDIUM" },
  { word: "OMBRA",     hint: "Segue ma non parla",                                           difficulty: "MEDIUM" },
  { word: "SILENZIO",  hint: "Parla più delle parole",                                       difficulty: "MEDIUM" },
  { word: "VIAGGIO",   hint: "Si fa con una valigia o con la mente",                         difficulty: "MEDIUM" },
  { word: "MISTERO",   hint: "Sherlock Holmes ne va a caccia",                               difficulty: "MEDIUM" },
  { word: "TESORO",    hint: "Long John Silver lo cercava",                                  difficulty: "MEDIUM" },
  { word: "MAPPA",     hint: "La X indica dove",                                             difficulty: "MEDIUM" },
  { word: "AVVENTURA", hint: "Tintin ne vive una",                                           difficulty: "MEDIUM" },
  { word: "FANTASMA",  hint: "Attraversa le pareti",                                         difficulty: "MEDIUM" },
  { word: "MAGIA",     hint: "Pronunciata con la bacchetta",                                 difficulty: "MEDIUM" },
  { word: "INCANTESIMO",hint: "Lanciato dalla strega",                                       difficulty: "MEDIUM" },
  { word: "PRINCIPESSA",hint: "Aspetta il bacio nel castello",                              difficulty: "MEDIUM" },
  { word: "CASTELLO",  hint: "Ha fossato e torri",                                           difficulty: "MEDIUM" },
  { word: "DRAGO",     hint: "Sputa fuoco nelle fiabe",                                      difficulty: "MEDIUM" },
  { word: "CAVALIERE", hint: "Armatura e spada al fianco",                                   difficulty: "MEDIUM" },
  { word: "SPADA",     hint: "Excalibur e Damocle",                                          difficulty: "MEDIUM" },
  { word: "CORONA",    hint: "Sulla testa del re",                                           difficulty: "MEDIUM" },
  { word: "TRONO",     hint: "Su cui siede il sovrano",                                      difficulty: "MEDIUM" },
  { word: "IMPERO",    hint: "Roma ne aveva uno grandissimo",                                difficulty: "MEDIUM" },
  { word: "BATTAGLIA", hint: "Scontro tra eserciti",                                         difficulty: "MEDIUM" },
  { word: "VITTORIA",  hint: "Dea alata e risultato agognato",                               difficulty: "MEDIUM" },
  { word: "CORAGGIO",  hint: "Quel che serve per affrontare la paura",                       difficulty: "MEDIUM" },
  { word: "PAURA",     hint: "Fa tremare le gambe",                                          difficulty: "MEDIUM" },
  { word: "FORTUNA",   hint: "Cieca secondo il detto",                                       difficulty: "MEDIUM" },
  { word: "FIDUCIA",   hint: "Si costruisce, si perde in un attimo",                         difficulty: "MEDIUM" },
  { word: "TRADIMENTO",hint: "Bruto e Cesare",                                               difficulty: "MEDIUM" },
  { word: "VERITA",    hint: "Nasce sempre a galla",                                         difficulty: "MEDIUM" },
  { word: "BUGIA",     hint: "Il naso di Pinocchio lo rivela",                               difficulty: "MEDIUM" },
  { word: "SEGRETO",   hint: "Si mantiene sotto le labbra",                                  difficulty: "MEDIUM" },
  { word: "SPERANZA",  hint: "Ultima dea a morire",                                          difficulty: "MEDIUM" },
  { word: "NOSTALGIA", hint: "Rimpianto del passato lontano",                                difficulty: "MEDIUM" },
  { word: "MALINCONIA",hint: "Tristezza dolce e riflessiva",                                 difficulty: "MEDIUM" },
  { word: "PASSIONE",  hint: "Brucia dentro",                                                difficulty: "MEDIUM" },
  { word: "GELOSIA",   hint: "Otello ne fu vittima",                                         difficulty: "MEDIUM" },
  { word: "RABBIA",    hint: "Ribolle e esplode",                                            difficulty: "MEDIUM" },
  { word: "ORGOGLIO",  hint: "Il primo dei pregiudizi",                                      difficulty: "MEDIUM" },
  { word: "UMILTA",    hint: "Virtù dei grandi",                                             difficulty: "MEDIUM" },
  { word: "SAGGEZZA",  hint: "Arriva con l'età",                                             difficulty: "MEDIUM" },
  { word: "GIUSTIZIA", hint: "Ha la bilancia e gli occhi bendati",                           difficulty: "MEDIUM" },
  { word: "LIBERTA",   hint: "La statua di New York",                                        difficulty: "MEDIUM" },
  { word: "PACE",      hint: "Colomba e ramoscello d'ulivo",                                 difficulty: "MEDIUM" },
  { word: "GUERRA",    hint: "Opposto della pace, spesso per il petrolio",                   difficulty: "MEDIUM" },
  { word: "RIVOLUZIONE",hint: "Francese nel 1789",                                           difficulty: "MEDIUM" },
  { word: "PATRIA",    hint: "Dolce è morire per lei",                                       difficulty: "MEDIUM" },
  { word: "BANDIERA",  hint: "Sventola sul pennone",                                         difficulty: "MEDIUM" },
  { word: "INNO",      hint: "Si canta in piedi",                                            difficulty: "MEDIUM" },
  { word: "MEDAGLIA",  hint: "Oro, argento o bronzo",                                        difficulty: "MEDIUM" },
  { word: "TROFEO",    hint: "Si alza al cielo dopo la vittoria",                            difficulty: "MEDIUM" },
  { word: "CAMPIONE",  hint: "Primo assoluto",                                               difficulty: "MEDIUM" },
  { word: "RECORD",    hint: "Usain Bolt li frantuma",                                       difficulty: "MEDIUM" },
  { word: "STADIO",    hint: "90 minuti di emozioni",                                        difficulty: "MEDIUM" },
  { word: "ARBITRO",   hint: "Fischia e ammonisce",                                          difficulty: "MEDIUM" },
  { word: "ALLENATORE",hint: "Dirige la squadra dalla panchina",                             difficulty: "MEDIUM" },
  { word: "TIFOSO",    hint: "Ultras senza biglietto non entra",                             difficulty: "MEDIUM" },
  { word: "SCUDETTO",  hint: "Tricolore sul petto",                                          difficulty: "MEDIUM" },
  { word: "CORSA",     hint: "Tempo che stringe, atleti che volano",                         difficulty: "MEDIUM" },
  { word: "MARATONA",  hint: "42 km e passa",                                                difficulty: "MEDIUM" },
  { word: "ORIZZONTE", hint: "Dove cielo e mare si incontrano",                              difficulty: "MEDIUM" },
  { word: "SPEDIZIONE",hint: "Marinai, Mille, Antartide",                                    difficulty: "MEDIUM" },
  { word: "BUSSOLA",   hint: "L'ago punta sempre a nord",                                    difficulty: "MEDIUM" },
  { word: "TELESCOPIO",hint: "Avvicina gli astri",                                           difficulty: "MEDIUM" },
  { word: "MICROSCOPIO",hint:"Rivela l'invisibile al contrario del telescopio",              difficulty: "MEDIUM" },
  { word: "LABORATORIO",hint: "Provette, camici e scoperte",                                 difficulty: "MEDIUM" },
  { word: "ESPERIMENTO",hint: "Prova che conferma l'ipotesi",                                difficulty: "MEDIUM" },
  { word: "INVENZIONE",hint: "Ruota, stampa, internet...",                                   difficulty: "MEDIUM" },
  { word: "MOTORE",    hint: "Cuore della macchina",                                         difficulty: "MEDIUM" },
  { word: "VELOCITA",  hint: "Kilometri orari e adrenalina",                                 difficulty: "MEDIUM" },
  { word: "CARBURANTE",hint: "Riempie il serbatoio",                                         difficulty: "MEDIUM" },
  { word: "STRATEGIA", hint: "Serve alla guerra e agli scacchi",                             difficulty: "MEDIUM" },
  { word: "SCACCHIERA",hint: "64 caselle bianche e nere",                                    difficulty: "MEDIUM" },
  { word: "LABIRINTO", hint: "Dedalo l'ha costruito a Creta",                                difficulty: "MEDIUM" },
  { word: "INDOVINELLO",hint: "La Sfinge lo poneva a Edipo",                                 difficulty: "MEDIUM" },
  { word: "ENIGMA",    hint: "Turing lo decifrò",                                            difficulty: "MEDIUM" },
  { word: "SIMBOLO",   hint: "Rappresenta più di quello che mostra",                         difficulty: "MEDIUM" },
  { word: "MESSAGGIO", hint: "Trasmesso fra due persone",                                    difficulty: "MEDIUM" },
  { word: "LETTERA",   hint: "Si affranca col francobollo",                                  difficulty: "MEDIUM" },
  { word: "FRANCOBOLLO",hint: "Gommato e con effigi",                                        difficulty: "MEDIUM" },
  { word: "POSTINO",   hint: "Porta buone e cattive notizie",                                difficulty: "MEDIUM" },
  { word: "GIORNALE",  hint: "Si legge al bar col caffè",                                    difficulty: "MEDIUM" },
  { word: "CRONACA",   hint: "I fatti del giorno",                                           difficulty: "MEDIUM" },
  { word: "REPORTER",  hint: "Microfono e taccuino in mano",                                 difficulty: "MEDIUM" },
  { word: "TELEVISIONE",hint: "Baird l'ha inventata",                                        difficulty: "MEDIUM" },
  { word: "CINEMA",    hint: "Buio, schermo grande, popcorn",                                difficulty: "MEDIUM" },
  { word: "TEATRO",    hint: "Sipario che si apre",                                          difficulty: "MEDIUM" },
  { word: "PALCO",     hint: "Dove recita chi fa spettacolo",                                difficulty: "MEDIUM" },
  { word: "SIPARIO",   hint: "Nasconde e rivela la scena",                                   difficulty: "MEDIUM" },
  { word: "MASCHERA",  hint: "Carnevale o Arlecchino",                                       difficulty: "MEDIUM" },
  { word: "CARNEVALE", hint: "A Venezia è famoso",                                           difficulty: "MEDIUM" },
  { word: "OPERA",     hint: "Aida e Traviata lo sono",                                      difficulty: "MEDIUM" },
  { word: "SINFONIA",  hint: "Nona di Beethoven",                                            difficulty: "MEDIUM" },
  { word: "CONCERTO",  hint: "Orchestra, solista e direttore",                               difficulty: "MEDIUM" },
  { word: "MELODIA",   hint: "Linea musicale che resta in testa",                            difficulty: "MEDIUM" },
  { word: "ARMONIA",   hint: "Accordo perfetto fra voci o parti",                            difficulty: "MEDIUM" },
  { word: "RITMO",     hint: "Cadenza della musica",                                         difficulty: "MEDIUM" },
  { word: "ORCHESTRA", hint: "Tutti gli strumenti insieme",                                  difficulty: "MEDIUM" },
  { word: "VIOLINO",   hint: "Stradivari li costruiva",                                      difficulty: "MEDIUM" },
  { word: "PIANOFORTE",hint: "88 tasti bianchi e neri",                                      difficulty: "MEDIUM" },

  // --- HARD (100) --- parole più rare, metafore, doppi sensi
  { word: "ETERNITA",   hint: "Il tempo che non finisce mai",                                difficulty: "HARD" },
  { word: "INFINITO",   hint: "Leopardi guardava oltre la siepe",                            difficulty: "HARD" },
  { word: "ABISSO",     hint: "Nietzsche ci avvertiva di non fissarlo",                      difficulty: "HARD" },
  { word: "ZENIT",      hint: "Il punto più alto del sole",                                  difficulty: "HARD" },
  { word: "NADIR",      hint: "Opposto del zenit",                                           difficulty: "HARD" },
  { word: "CREPUSCOLO", hint: "La luce che muore a ovest",                                   difficulty: "HARD" },
  { word: "AURORA",     hint: "Dita di rosa nell'Iliade",                                    difficulty: "HARD" },
  { word: "ALBA",       hint: "Fine della notte, inizio del giorno",                         difficulty: "HARD" },
  { word: "TRAMONTO",   hint: "Il sole si corica",                                           difficulty: "HARD" },
  { word: "MIRAGGIO",   hint: "Oasi che non c'è",                                            difficulty: "HARD" },
  { word: "ILLUSIONE",  hint: "Ottica o sentimentale",                                       difficulty: "HARD" },
  { word: "UTOPIA",     hint: "Thomas More e il luogo perfetto",                             difficulty: "HARD" },
  { word: "DISTOPIA",   hint: "1984 di Orwell",                                              difficulty: "HARD" },
  { word: "MELANCOLIA", hint: "Dürer la incise",                                             difficulty: "HARD" },
  { word: "EUFORIA",    hint: "Felicità estrema e incontenibile",                            difficulty: "HARD" },
  { word: "ESTASI",     hint: "Santa Teresa di Bernini",                                     difficulty: "HARD" },
  { word: "EPIFANIA",   hint: "Rivelazione improvvisa, dodici giorni dopo Natale",           difficulty: "HARD" },
  { word: "METAMORFOSI",hint: "Ovidio e Kafka ne hanno scritto",                             difficulty: "HARD" },
  { word: "TRASFORMAZIONE",hint: "Cambio di forma profondo",                                 difficulty: "HARD" },
  { word: "ALCHIMIA",   hint: "Trasformava piombo in oro",                                   difficulty: "HARD" },
  { word: "ELISIR",     hint: "Bevanda miracolosa, anche di Donizetti",                      difficulty: "HARD" },
  { word: "AMBROSIA",   hint: "Cibo degli dei greci",                                        difficulty: "HARD" },
  { word: "NETTARE",    hint: "Bevanda dell'Olimpo",                                         difficulty: "HARD" },
  { word: "OLIMPO",     hint: "Dimora di Zeus",                                              difficulty: "HARD" },
  { word: "PARNASO",    hint: "Monte delle Muse",                                            difficulty: "HARD" },
  { word: "LETE",       hint: "Fiume degli inferi, fa dimenticare",                          difficulty: "HARD" },
  { word: "CARONTE",    hint: "Traghetta le anime",                                          difficulty: "HARD" },
  { word: "AVERNO",     hint: "Regno infernale nell'antichità",                              difficulty: "HARD" },
  { word: "LIMBO",      hint: "Primo cerchio dell'aldilà dantesco",                          difficulty: "HARD" },
  { word: "PURGATORIO", hint: "Dante ci sale leggero",                                       difficulty: "HARD" },
  { word: "PARADISO",   hint: "Terzo regno della Commedia",                                  difficulty: "HARD" },
  { word: "REDENZIONE", hint: "Riscatto dopo il peccato",                                    difficulty: "HARD" },
  { word: "ESPIAZIONE", hint: "Pena che lava la colpa",                                      difficulty: "HARD" },
  { word: "PENITENZA",  hint: "Pegno del peccatore",                                         difficulty: "HARD" },
  { word: "PELLEGRINO", hint: "Chi cammina verso il sacro",                                  difficulty: "HARD" },
  { word: "PELLEGRINAGGIO",hint: "Viaggio verso un luogo santo",                             difficulty: "HARD" },
  { word: "SANTUARIO",  hint: "Tempio dedicato",                                             difficulty: "HARD" },
  { word: "RELIQUIA",   hint: "Resto venerato di un santo",                                  difficulty: "HARD" },
  { word: "ICONA",      hint: "Sacra immagine bizantina, oggi anche digitale",               difficulty: "HARD" },
  { word: "AFFRESCO",   hint: "Dipinto sull'intonaco fresco",                                difficulty: "HARD" },
  { word: "MOSAICO",    hint: "Fatto di tessere colorate",                                   difficulty: "HARD" },
  { word: "BASSORILIEVO",hint:"Scultura poco sporgente",                                     difficulty: "HARD" },
  { word: "CARIATIDE",  hint: "Colonna a forma di donna",                                    difficulty: "HARD" },
  { word: "COLONNA",    hint: "Sorregge e commemora",                                        difficulty: "HARD" },
  { word: "OBELISCO",   hint: "Monolito a punta, spesso egizio",                             difficulty: "HARD" },
  { word: "PIRAMIDE",   hint: "Tomba dei faraoni",                                           difficulty: "HARD" },
  { word: "SARCOFAGO",  hint: "Contiene il sonno eterno",                                    difficulty: "HARD" },
  { word: "CATACOMBA",  hint: "Cimitero sotterraneo antico",                                 difficulty: "HARD" },
  { word: "NECROPOLI",  hint: "Città dei morti",                                             difficulty: "HARD" },
  { word: "MAUSOLEO",   hint: "Grandioso monumento funebre",                                 difficulty: "HARD" },
  { word: "CENOTAFIO",  hint: "Monumento vuoto in memoria",                                  difficulty: "HARD" },
  { word: "EPITAFFIO",  hint: "Scritta sulla lapide",                                        difficulty: "HARD" },
  { word: "ELEGIA",     hint: "Canto di lamento",                                            difficulty: "HARD" },
  { word: "OVAZIONE",   hint: "Applauso fragoroso e prolungato",                             difficulty: "HARD" },
  { word: "CATARSI",    hint: "Liberazione emotiva dopo la tragedia",                        difficulty: "HARD" },
  { word: "TRAGEDIA",   hint: "Sofocle e Shakespeare",                                       difficulty: "HARD" },
  { word: "COMMEDIA",   hint: "Dante la chiamò così",                                        difficulty: "HARD" },
  { word: "ODISSEA",    hint: "Viaggio lungo e pieno di peripezie",                          difficulty: "HARD" },
  { word: "PERIPEZIA",  hint: "Rovescio drammatico nel racconto",                            difficulty: "HARD" },
  { word: "EPILOGO",    hint: "Le ultime parole del libro",                                  difficulty: "HARD" },
  { word: "PROLOGO",    hint: "Introduzione prima del dramma",                               difficulty: "HARD" },
  { word: "PREAMBOLO",  hint: "Discorso che precede la sostanza",                            difficulty: "HARD" },
  { word: "RUBRICA",    hint: "Spazio fisso del giornale",                                   difficulty: "HARD" },
  { word: "ARCHIVIO",   hint: "Dove dormono i documenti",                                    difficulty: "HARD" },
  { word: "MANOSCRITTO",hint: "Scritto a mano, prima della stampa",                          difficulty: "HARD" },
  { word: "INCUNABOLO", hint: "Libro stampato prima del 1501",                               difficulty: "HARD" },
  { word: "PERGAMENA",  hint: "Pelle animale per scrivere",                                  difficulty: "HARD" },
  { word: "PAPIRO",     hint: "Supporto di scrittura egizio",                                difficulty: "HARD" },
  { word: "GEROGLIFICO",hint: "Scrittura sulla parete della tomba",                          difficulty: "HARD" },
  { word: "CUNEIFORME", hint: "Scrittura sumera a cunei",                                    difficulty: "HARD" },
  { word: "ALFABETO",   hint: "26 segni in italiano",                                        difficulty: "HARD" },
  { word: "LINGUAGGIO", hint: "Binario, dei fiori, del corpo",                               difficulty: "HARD" },
  { word: "IDIOMA",     hint: "Lingua caratteristica di un popolo",                          difficulty: "HARD" },
  { word: "DIALETTO",   hint: "Sfumatura linguistica locale",                                difficulty: "HARD" },
  { word: "SLANG",      hint: "Gergo informale",                                             difficulty: "HARD" },
  { word: "METAFORA",   hint: "Figura retorica di trasferimento",                            difficulty: "HARD" },
  { word: "OSSIMORO",   hint: "Silenzio assordante, ghiaccio bollente",                      difficulty: "HARD" },
  { word: "PARADOSSO",  hint: "Gemelli di Einstein",                                         difficulty: "HARD" },
  { word: "ENIGMISTA",  hint: "Chi crea rebus e cruciverba",                                 difficulty: "HARD" },
  { word: "CRUCIVERBA", hint: "Griglia di parole incrociate",                                difficulty: "HARD" },
  { word: "REBUS",      hint: "Immagini che nascondono una frase",                           difficulty: "HARD" },
  { word: "ANAGRAMMA",  hint: "Stesse lettere, altro significato",                           difficulty: "HARD" },
  { word: "PALINDROMO", hint: "Si legge uguale anche al contrario",                          difficulty: "HARD" },
  { word: "ACROSTICO",  hint: "Iniziali che formano una parola",                             difficulty: "HARD" },
  { word: "SONETTO",    hint: "14 versi e due terzine",                                      difficulty: "HARD" },
  { word: "TERZINA",    hint: "Strofa di tre versi, cara a Dante",                           difficulty: "HARD" },
  { word: "ENDECASILLABO",hint:"Verso di undici sillabe, il più nobile",                     difficulty: "HARD" },
  { word: "ALLITTERAZIONE",hint:"Ripetizione di suoni uguali",                               difficulty: "HARD" },
  { word: "ONOMATOPEA", hint: "Suono che imita il significato",                              difficulty: "HARD" },
  { word: "IPERBOLE",   hint: "Esagerazione retorica o curva matematica",                    difficulty: "HARD" },
  { word: "LITOTE",     hint: "Negare il contrario per affermare",                           difficulty: "HARD" },
  { word: "SINESTESIA", hint: "Un colore che ha sapore",                                     difficulty: "HARD" },
  { word: "ANAFORA",    hint: "Ripetizione in apertura di verso",                            difficulty: "HARD" },
  { word: "ENJAMBEMENT",hint: "Frase che sconfina al verso successivo",                      difficulty: "HARD" },
  { word: "CESURA",     hint: "Pausa nel mezzo del verso",                                   difficulty: "HARD" },
  { word: "APOCOPE",    hint: "Caduta della vocale finale",                                  difficulty: "HARD" },
  { word: "AFERESI",    hint: "Caduta della vocale iniziale",                                difficulty: "HARD" },
  { word: "ETIMOLOGIA", hint: "Studio dell'origine delle parole",                            difficulty: "HARD" },
  { word: "TOPONIMO",   hint: "Nome proprio di luogo",                                       difficulty: "HARD" },
  { word: "ANTONOMASIA",hint: "Un nome che ne sostituisce un altro comune",                  difficulty: "HARD" },
  { word: "PERIFRASI",  hint: "Dire con più parole ciò che si direbbe con una",              difficulty: "HARD" },
  { word: "EUFEMISMO",  hint: "Parola gentile per una dura",                                 difficulty: "HARD" },
];

async function main() {
  console.log(`🎯 Seed GHIGLIOTTINA — ${ENTRIES.length} frasi\n`);

  // Categoria dedicata
  const cat = await prisma.category.upsert({
    where: { slug: "ghigliottina" },
    update: { name: "Ghigliottina", icon: "🎯", color: "#dc2626" },
    create: { name: "Ghigliottina", slug: "ghigliottina", icon: "🎯", color: "#dc2626" },
  });

  let created = 0;
  let skipped = 0;

  for (const e of ENTRIES) {
    const exists = await prisma.question.findFirst({
      where: { categoryId: cat.id, type: "GHIGLIOTTINA", openAnswer: e.word },
    });
    if (exists) { skipped++; continue; }

    await prisma.question.create({
      data: {
        text: e.hint,
        type: "GHIGLIOTTINA",
        difficulty: e.difficulty,
        timeLimit: 60,
        categoryId: cat.id,
        openAnswer: e.word,
      },
    });
    created++;
  }

  const total = await prisma.question.count({ where: { type: "GHIGLIOTTINA" } });
  console.log(`✅ Create: ${created}, saltate (già presenti): ${skipped}`);
  console.log(`📊 Totale GHIGLIOTTINA nel DB: ${total}`);
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
